export enum ApiPathsEnum {
	api = "api",
	users = "users",
	leads = "leads",
	login = "login",
	register = "register",
	user = "user",
	delete = "delete",
	create = "create",
	id = ":id",
	username = ":username",
	allUsers = "allUsers",
	allLeads = "allLeads",
	createLead = "createLead",
	createLeadMany = "createLeadMany",
	getLeadById = "getLeadById",
	leadModel = "leadModel",
	updateLeadById = "updateLeadById",
	deleteLeadByEmail = "deleteLeadByEmail",
	moduleModel = "moduleModel",
	
}
